### PR TITLE
Bugfix/static layer activate

### PR DESCRIPTION
**Pull request by howardcochran**
Fix ability to deactivate and reactivate static costmap layer and still receive a new map.

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/3)

### CODE REVIEW

**Comment by c-andy-martin** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[costmap_2d/plugins/static_layer.cpp, line 84 at r2](https://beta.reviewable.io/reviews/badgertechnologies/navigation/3#-LAncaa_C-kZ-M_v-faa:-LAncaa_C-kZ-M_v-fab:b-rdv4ul) ([raw file](https://github.com/badgertechnologies/navigation/blob/e0f76fcb269b5d748c1b446152c8db6627364fc9/costmap_2d/plugins/static_layer.cpp#L84)):*
> ```cpp
> 
>   // Only resubscribe if topic has changed
>   if (!first_map_only_ || map_sub_.getTopic() != ros::names::resolve(map_topic))
> ```

its unfortuante that when a subscriber is suspended that getTopic still returns the old name. I'm ok with this, but it's not straightforward and doesn't match the comment above. Maybe we should add to the comment?

---

*[move_base/src/move_base.cpp, line 816 at r2](https://beta.reviewable.io/reviews/badgertechnologies/navigation/3#-LAnZh--4IRiP5BgHIGM:-LAnZh--4IRiP5BgHIGN:b-nwglj9) ([raw file](https://github.com/badgertechnologies/navigation/blob/e0f76fcb269b5d748c1b446152c8db6627364fc9/move_base/src/move_base.cpp#L816)):*
> ```cpp
> 
>     if (prefer_prev & persistence_end_ != PERSISTENCE_INITIAL)
>     {
> ```

I prefer not to change the layout of upstream code, it will make merging harder, right?

---

*[move_base/src/move_base.cpp, line 823 at r2](https://beta.reviewable.io/reviews/badgertechnologies/navigation/3#-LAnZUwG9RcjALkj8u-r:-LAnZUwG9RcjALkj8u-s:bg7vtmo) ([raw file](https://github.com/badgertechnologies/navigation/blob/e0f76fcb269b5d748c1b446152c8db6627364fc9/move_base/src/move_base.cpp#L823)):*
> ```cpp
>       if (now < persistence_end_)
>       {
>         ROS_DEBUG_STREAM("Keeping PREV plan. Time remain="
> ```

Seems like a lot of changes just for changing debugging. We are no longer outputing to another logging stream, and the format of the prints is different. Seems a lot simpler to just change `ROS_ERROR_NAMED` to `ROS_DEBUG_NAMED` and be done with it.

---

*[move_base/src/move_base.cpp, line 832 at r2](https://beta.reviewable.io/reviews/badgertechnologies/navigation/3#-LAnZfD83wwuvACUWyyu:-LAnZfD83wwuvACUWyyv:benpsw9) ([raw file](https://github.com/badgertechnologies/navigation/blob/e0f76fcb269b5d748c1b446152c8db6627364fc9/move_base/src/move_base.cpp#L832)):*
> ```cpp
>     }
>     persistence_end_ = PERSISTENCE_NEWPLAN;
>     ROS_DEBUG_STREAM("Using NEW plan. Prev plan len: " << prev_plan_len
> ```

Same comment as above.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/badgertechnologies/navigation/3)*

**Review by c-andy-martin — APPROVED** [review]

**Comment by howardcochran** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[costmap_2d/plugins/static_layer.cpp, line 84 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/3#-LAncaa_C-kZ-M_v-faa:-LAs58jM87XRdpG1Kh41:bzigkrv) ([raw file](https://github.com/badgertechnologies/navigation/blob/e0f76fcb269b5d748c1b446152c8db6627364fc9/costmap_2d/plugins/static_layer.cpp#L84)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

its unfortuante that when a subscriber is suspended that getTopic still returns the old name. I'm ok with this, but it's not straightforward and doesn't match the comment above. Maybe we should add to the comment?
</blockquote></details>

I rewrote this commit with a reworded comment.

---

*[move_base/src/move_base.cpp, line 816 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/3#-LAnZh--4IRiP5BgHIGM:-LAs5_4pDusdms9TfOhC:b-a2lcot) ([raw file](https://github.com/badgertechnologies/navigation/blob/e0f76fcb269b5d748c1b446152c8db6627364fc9/move_base/src/move_base.cpp#L816)):*
> Cleanups of my code from last spring
Cleanups of my code from last spring

---

*[move_base/src/move_base.cpp, line 823 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/3#-LAnZUwG9RcjALkj8u-r:-LAs5Joj8HFNMDKWwcwy:b2e5g2z) ([raw file](https://github.com/badgertechnologies/navigation/blob/e0f76fcb269b5d748c1b446152c8db6627364fc9/move_base/src/move_base.cpp#L823)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Seems like a lot of changes just for changing debugging. We are no longer outputing to another logging stream, and the format of the prints is different. Seems a lot simpler to just change `ROS_ERROR_NAMED` to `ROS_DEBUG_NAMED` and be done with it.
</blockquote></details>

This was my code to begin with, written in a hurry at customer's site last spring, so this commit cleans it up substantially.

---

*[move_base/src/move_base.cpp, line 832 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/3#-LAnZfD83wwuvACUWyyu:-LAs5WqoCNp7OQIUCr9N:bbgki0t) ([raw file](https://github.com/badgertechnologies/navigation/blob/e0f76fcb269b5d748c1b446152c8db6627364fc9/move_base/src/move_base.cpp#L832)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Same comment as above.
</blockquote></details>

Cleanups of my code from last spring

---


*Comments from [Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/3)*

**Comment by howardcochran** [comment]
Reviewed 1 of 1 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/3)*

**Comment by c-andy-martin** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/3)*

**Pull request merged**
