### PR TITLE
costmap_3d: add nonlethal query, distance options

### PR DESCRIPTION
**Pull request by c-andy-martin**
Add the ability to query nonlethal only obstacles.
A nonlethal obstacle is any Cost between FREE and LETHAL.

Also, extend the distance interface to be passed a DistanceOptions
object. This improves the interface by naming each option.

Add an option to the new interface to limit distance. This is useful
for collision checking or for limiting the distance queries

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/23)

### CODE REVIEW

**Review by jtravis-nj — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/23)* status: all files reviewed, 1 unresolved discussion (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/include/costmap_3d/octree_solver.h, line 160 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/23#-M7Ot5oECnArbxj-Ch0s:-M7Ot5oECnArbxj-Ch0t:b-kou4rz) ([raw file](https://github.com/badgertechnologies/navigation/blob/6b29268243485b03086107994ebdbc4c590ba209/costmap_3d/include/costmap_3d/octree_solver.h#L160)):*
> ```objc
>     return uncertain_only_ ?
>         (tree->nodeHasChildren(node) ? !tree->isNodeFree(node) : tree->isNodeUncertain(node)) :
>         tree->isNodeOccupied(node);
> ```

This code doesn't seem to descend if the cost is lethal. The comment insinuates this is desired.  I assume this is more of a note for a future improvement?

**Review by howardcochran — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/23)* status: all files reviewed, 2 unresolved discussions (waiting on @c-andy-martin)

___
*[costmap_3d/src/costmap_3d_query.cpp, line 445 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/23#-M7PFb4tBrsjp0a87YGA:-M7PFb4tBrsjp0a87YGB:b-iiin8g) ([raw file](https://github.com/badgertechnologies/navigation/blob/6b29268243485b03086107994ebdbc4c590ba209/costmap_3d/src/costmap_3d_query.cpp#L445)):*
> ```cpp
>   opts.distance_limit = std::numeric_limits<double>::min();
>   // We want exact answers for collision only checks.
>   opts.relative_error = 0.0;
> ```

Several DistanceOptions fields are left uninitialized here, as they are primitive types in a simple struct.

**Review by howardcochran — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/23)* status: all files reviewed, 1 unresolved discussion (waiting on @c-andy-martin)

___
*[costmap_3d/src/costmap_3d_query.cpp, line 704 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/23#-M7PGjCkEGeKS8_-kPRP:-M7PGjCkEGeKS8_-kPRQ:b-e5rfa) ([raw file](https://github.com/badgertechnologies/navigation/blob/6b29268243485b03086107994ebdbc4c590ba209/costmap_3d/src/costmap_3d_query.cpp#L704)):*
> ```cpp
>           cache_entry->second,
>           pose);
>       if (distance < pose_distance)
> ```

This appears to be a bug fix unrelated to the new function. If that is correct, you might want to consider making it a separate commit.

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/23)* status: all files reviewed, 1 unresolved discussion (waiting on @jtravis-nj)

___
*[costmap_3d/include/costmap_3d/octree_solver.h, line 160 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/23#-M7Ot5oECnArbxj-Ch0s:-M7tpUfWDefYpCHSsF-k:boubhxg) ([raw file](https://github.com/badgertechnologies/navigation/blob/6b29268243485b03086107994ebdbc4c590ba209/costmap_3d/include/costmap_3d/octree_solver.h#L160)):*
<details><summary><i>Previously, jtravis-nj (Jacob Travis) wrote…</i></summary><blockquote>

This code doesn't seem to descend if the cost is lethal. The comment insinuates this is desired.  I assume this is more of a note for a future improvement?
</blockquote></details>

It actually does, if nodeHasChildren, then its an inner node. We go down if its !FREE (so anything above FREE, which includes all of nonlethal and lethal). Then once at a leaf (no children) we can only go further if the node is uncertain.
___
*[costmap_3d/src/costmap_3d_query.cpp, line 445 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/23#-M7PFb4tBrsjp0a87YGA:-M7tpi5JANzIFBraTlHG:b7q1izz) ([raw file](https://github.com/badgertechnologies/navigation/blob/6b29268243485b03086107994ebdbc4c590ba209/costmap_3d/src/costmap_3d_query.cpp#L445)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Several DistanceOptions fields are left uninitialized here, as they are primitive types in a simple struct.
</blockquote></details>

They are initialized with default values (see the declaration of DistanceOptions)
___
*[costmap_3d/src/costmap_3d_query.cpp, line 704 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/23#-M7PGjCkEGeKS8_-kPRP:-M7tr1OkA9f9Rawg75Qg:b4q32zb) ([raw file](https://github.com/badgertechnologies/navigation/blob/6b29268243485b03086107994ebdbc4c590ba209/costmap_3d/src/costmap_3d_query.cpp#L704)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

This appears to be a bug fix unrelated to the new function. If that is correct, you might want to consider making it a separate commit.
</blockquote></details>

this is actually a related change. until this change set there was no way to limit the distance being queried by the API. now it can be artificially limited, which can mean that a cache hit is further away than a cache hit. so now we must check that we aren't overriding the passed in limit.

**Review by howardcochran — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/23)* status: all files reviewed, 1 unresolved discussion (waiting on @jtravis-nj)

**Pull request merged**
