### PR TITLE
costmap_3d: add ability to query left/right

### PR DESCRIPTION
**Pull request by c-andy-martin**
Add the option to query only left or right of the given pose.
This option ignores the region of the map on the other side for the
queries.

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/16)

### CODE REVIEW

**Review by howardcochran — APPROVED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/16)* status: all files reviewed, 1 unresolved discussion (waiting on @c-andy-martin)

___
*[costmap_3d/src/costmap_3d_query.cpp, line 69 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/16#-M40BcsM42sYEq6qqDgB:-M40BcsM42sYEq6qqDgC:btt5lyv) ([raw file](https://github.com/badgertechnologies/navigation/blob/07de82601c85083af3321ece40712524beea8fbd/costmap_3d/src/costmap_3d_query.cpp#L69)):*
> ```cpp
>     pose_micro_bins_per_radian_(pose_micro_bins_per_radian)
> {
>   last_cache_entries_.resize(MAX);
> ```

It may be very slightly better to put `last_cache_entries_(3)` in the constructor's initializer list instead.
___
*[costmap_3d/src/costmap_3d_query.cpp, line 534 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/16#-M40E1W98ruwi3Njq6RK:-M40E1W98ruwi3Njq6RL:b-1zya4a) ([raw file](https://github.com/badgertechnologies/navigation/blob/eb7f9b8c8327fc0b1f6a963ed906175bfa982580/costmap_3d/src/costmap_3d_query.cpp#L534)):*
> ```cpp
>     cache_entry->second.setupResult(&result);
>   }
>   else if(!milli_hit && distance_cache_.size() > 0)
> ```

It is unclear to me why you're deleting the milli-cache here altogether.

**Comment by c-andy-martin** [comment]
___
*[costmap_3d/src/costmap_3d_query.cpp, line 534 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/16#-M40E1W98ruwi3Njq6RK:-M40RcgS2YK4Cd6Vc5z-:bpnonin) ([raw file](https://github.com/badgertechnologies/navigation/blob/eb7f9b8c8327fc0b1f6a963ed906175bfa982580/costmap_3d/src/costmap_3d_query.cpp#L534)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

It is unclear to me why you're deleting the milli-cache here altogether.
</blockquote></details>

I'm not seeing anything in this area about deleting the milli-cache, did this comment mean to go somewhere else?

**Comment by c-andy-martin** [comment]
___
*[costmap_3d/src/costmap_3d_query.cpp, line 534 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/16#-M40E1W98ruwi3Njq6RK:-M40TIYA6xyas7XV4sJ9:b-tjxf3y) ([raw file](https://github.com/badgertechnologies/navigation/blob/eb7f9b8c8327fc0b1f6a963ed906175bfa982580/costmap_3d/src/costmap_3d_query.cpp#L534)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm not seeing anything in this area about deleting the milli-cache, did this comment mean to go somewhere else?
</blockquote></details>

ah,  this code here does not work correctly anymore, as the cache entries have different region types mixed in. This code that is deleted is saying, "we missed the milli cache, we missed the regular cache, and the regular cache has something in it. Let's just blindly use the first thing in the cache as a better guess than nothing" but I can't do that know that the first thing might be a LEFT region and I'm querying RIGHT for instance. This bit of code was more useful when there was not a last_cache as the last_cache is almost always there, and is indexed by region now. So I just opted to remove it since it provided little benefit and is now broken.

**Comment by c-andy-martin** [comment]
___
*[costmap_3d/src/costmap_3d_query.cpp, line 69 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/16#-M40BcsM42sYEq6qqDgB:-M40TxXY31JYEYD4KoUU:b-7ql1td) ([raw file](https://github.com/badgertechnologies/navigation/blob/07de82601c85083af3321ece40712524beea8fbd/costmap_3d/src/costmap_3d_query.cpp#L69)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

It may be very slightly better to put `last_cache_entries_(3)` in the constructor's initializer list instead.
</blockquote></details>

fixed

**Pull request merged**
