### PR TITLE
AMCL: new motion model, new sensor model, new sampling model, new global-localization tracking, etc.

### PR DESCRIPTION
**Pull request by c-andy-martin**
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/6)

### CODE REVIEW

**Comment by c-andy-martin** [comment]
the following graph may prove useful in understanding the gompertz sensor model. Basically, in that model, I'm using a gompertz function to transform the sensor likelihood into the sample weight multiplier. The way I have the gompertz function configured (which isn't even in the AMCL PR, as its in ant_navigation), results in the sigmoid response seen in the graph. This is a desirable response, as it weights scans which mostly match roughly the same, and doesn't under weight non-matches, which happen a lot under noisy conditions. The yellow line is the way AMCL is configured today. The blue was my first attempt at improving things using AMCL's likelihood_prob model. To overcome the sharp response when matching well, I added the gompertz model. Note: the max_beams is 60, so 60 in the x-axis means all beams matched perfectly, 0 means no beams matched at all.

gompertz
￼
If you are worried about CPU w/ gompertz, the transform is only applied at the end, after matching all the beams, so only happens for each particle on each update cycle (not the long pole in performance).

**Review by 12tbuchman — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/6)* status: 2 of 12 files reviewed, all discussions resolved (waiting on @12tbuchman, @howardcochran, and @travisariggs)

**Review by travisariggs — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, 4 of 4 files at r7, 4 of 4 files at r8, 4 of 4 files at r9, 4 of 4 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/6)* status: all files reviewed, 8 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[amcl/include/amcl/sensors/amcl_laser.h, line 96 at r8](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXdjELYBWPsjS6hZhgX:-LXdjELYBWPsjS6hZhgY:b-p1ef8x) ([raw file](https://github.com/badgertechnologies/navigation/blob/b878e36dcf04e680ae52a5341680fbea4fc14bf6/amcl/include/amcl/sensors/amcl_laser.h#L96)):*
> ```
>               double non_free_space_factor,
>               double non_free_space_radius);
> ```

Should these line up with the first arg?
___
*[amcl/include/amcl/sensors/amcl_odom.h, line 74 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXdRR4F6PyAPFku0Ax6:-LXdRR4F6PyAPFku0Ax7:b-d8lqev) ([raw file](https://github.com/badgertechnologies/navigation/blob/9e28d9bd48d1018de43aaa0558672067520a5033/amcl/include/amcl/sensors/amcl_odom.h#L74)):*
> ```
>   public: void SetModelOmni(double alpha1,
>                             double alpha2,
>                             double alpha3,
> ```

Trailing spaces?
___
*[amcl/src/amcl_node.cpp, line 1006 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXd_CQ17I1NP6L5iucP:-LXd_CQ17I1NP6L5iucQ:b4to1pv) ([raw file](https://github.com/badgertechnologies/navigation/blob/9e28d9bd48d1018de43aaa0558672067520a5033/amcl/src/amcl_node.cpp#L1006)):*
<details><summary><i alt="summary">Quoted 26 lines of code…</i></summary>

> ```
>     delta.v[0] = pose.v[0] - odom_integrator_last_pose_.v[0];
>     delta.v[1] = pose.v[1] - odom_integrator_last_pose_.v[1];
>     delta.v[2] = angle_diff(pose.v[2], odom_integrator_last_pose_.v[2]);
>  
>     // project bearing change onto average orientation, x is forward translation, y is strafe
>     double delta_trans, delta_rot, delta_bearing;
>     delta_trans = sqrt(delta.v[0]*delta.v[0] + delta.v[1]*delta.v[1]);
>     delta_rot = delta.v[2];
>     if (delta_trans < 1e-6)
>     {
>       // For such a small translation, we either didn't move or rotated in place.
>       // Assume the very small motion was forward, not strafe.
>       delta_bearing = 0;
>     }
>     else
>     {
>       delta_bearing = angle_diff(atan2(delta.v[1], delta.v[0]),
>                                  odom_integrator_last_pose_.v[2] + delta_rot/2);
>     }
>     double cs_bearing = cos(delta_bearing);
>     double sn_bearing = sin(delta_bearing);
>  
>     // Accumulate absolute motion
>     odom_integrator_absolute_motion_.v[0] += fabs(delta_trans * cs_bearing);
>     odom_integrator_absolute_motion_.v[1] += fabs(delta_trans * sn_bearing);
>     odom_integrator_absolute_motion_.v[2] += fabs(delta_rot);
> ```
</details>


I haven't gone through the math by hand on this section, but it seems to me that we could just jump to the end and add the absolute values of the x, y, and yaw deltas to the `odom_integrator_absolute_motion_`.  The only difference I can see is that we are zeroing out any bearing change if the translation was really, really small.  Does that if statement actually execute that often?  Is there something else that I'm missing?
___
*[amcl/src/amcl_node.cpp, line 1195 at r12](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXe3Ea--8fFsUrPB8Jd:-LXe3Ea--8fFsUrPB8Je:b-iwedvb) ([raw file](https://github.com/badgertechnologies/navigation/blob/a1037e0487a57b0c6ad4ae4d567a6c0b62815f35/amcl/src/amcl_node.cpp#L1195)):*
> ```cpp
>     p.v[0] = MAP_WXGX(map, free_point.first);
>     p.v[1] = MAP_WYGY(map, free_point.second);
>     p.v[2] = drand48() * 2 * M_PI - M_PI;
> ```

It would be awesome if we could rely on our magnetometer here to give us better guesses at our orientation...something for the future...
___
*[amcl/src/amcl_node.cpp, line 1200 at r12](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXe2LII21tCeiNrsom6:-LXe2LII21tCeiNrsom7:b-e5gxb5) ([raw file](https://github.com/badgertechnologies/navigation/blob/a1037e0487a57b0c6ad4ae4d567a6c0b62815f35/amcl/src/amcl_node.cpp#L1200)):*
> ```cpp
>     // Begin with the configured starting weight threshold,
>     // then down-weight each try by the configured deweight multiplier.
>     // A starting weight of 0 or negative means disable this check.
> ```

If the `uniform_pose_starting_weight_threshold_` is zero, will this be an infinite loop?
___
*[amcl/src/amcl_node.cpp, line 1222 at r12](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXe2gWP1ZcLOaKYJAwk:-LXe2gWP1ZcLOaKYJAwl:b-bwapsd) ([raw file](https://github.com/badgertechnologies/navigation/blob/a1037e0487a57b0c6ad4ae4d567a6c0b62815f35/amcl/src/amcl_node.cpp#L1222)):*
> ```cpp
>       {
>         // relax our criteria a bit to ensure we will eventually return
>         good_weight *= deweight_multiplier;
> ```

Just for my understanding, does this mean that we try to get a better pose, but if we try and try, we still end up with an almost totally random seed pose?  I guess this still makes it more likely that we will get a better seed pose.
___
*[amcl/src/amcl_node.cpp, line 1250 at r13](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXe4OESBt5Z4am8X4gV:-LXe4OESBt5Z4am8X4gW:b-jl7h5n) ([raw file](https://github.com/badgertechnologies/navigation/blob/77cba6dc90aa5c30efcc7399f3b6388852d6487f/amcl/src/amcl_node.cpp#L1250)):*
> ```cpp
>     return true;
>   }
>   boost::recursive_mutex::scoped_lock gl(configuration_mutex_);
> ```

Just for my understanding, is the localizer multithreaded?  Is that why we have a lock?
___
*[amcl/src/amcl/sensors/amcl_odom.cpp, line 97 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXdbf92-y-kNq4RZxDY:-LXdbf92-y-kNq4RZxDZ:bepwez7) ([raw file](https://github.com/badgertechnologies/navigation/blob/9e28d9bd48d1018de43aaa0558672067520a5033/amcl/src/amcl/sensors/amcl_odom.cpp#L97)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                        double alpha2,
>                        double alpha3,
>                        double alpha4,
>                        double alpha5)
> ```
</details>


Should these args line up with the first argument?

**Comment by c-andy-martin** [comment]
___
*[amcl/include/amcl/sensors/amcl_odom.h, line 74 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXdRR4F6PyAPFku0Ax6:-LXeIjl3656Sm_tB3XSl:b-q4inz7) ([raw file](https://github.com/badgertechnologies/navigation/blob/9e28d9bd48d1018de43aaa0558672067520a5033/amcl/include/amcl/sensors/amcl_odom.h#L74)):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

> ```
>   public: void SetModelOmni(double alpha1,
>                             double alpha2,
>                             double alpha3,
> ```

Trailing spaces?
</blockquote></details>

Yes, but this is not code I changed. I don't want to fix this whitespace issue right now, I was trying to not change code outside the scope of what I was doing.

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl_node.cpp, line 1006 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXd_CQ17I1NP6L5iucP:-LXeIui3AZ5wT-R6nXeO:b-47wxd7) ([raw file](https://github.com/badgertechnologies/navigation/blob/9e28d9bd48d1018de43aaa0558672067520a5033/amcl/src/amcl_node.cpp#L1006)):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

> ```
>     delta.v[0] = pose.v[0] - odom_integrator_last_pose_.v[0];
>     delta.v[1] = pose.v[1] - odom_integrator_last_pose_.v[1];
>     delta.v[2] = angle_diff(pose.v[2], odom_integrator_last_pose_.v[2]);
>  
>     // project bearing change onto average orientation, x is forward translation, y is strafe
>     double delta_trans, delta_rot, delta_bearing;
>     delta_trans = sqrt(delta.v[0]*delta.v[0] + delta.v[1]*delta.v[1]);
>     delta_rot = delta.v[2];
>     if (delta_trans < 1e-6)
>     {
>       // For such a small translation, we either didn't move or rotated in place.
>       // Assume the very small motion was forward, not strafe.
>       delta_bearing = 0;
>     }
>     else
>     {
>       delta_bearing = angle_diff(atan2(delta.v[1], delta.v[0]),
>                                  odom_integrator_last_pose_.v[2] + delta_rot/2);
>     }
>     double cs_bearing = cos(delta_bearing);
>     double sn_bearing = sin(delta_bearing);
>  
>     // Accumulate absolute motion
>     odom_integrator_absolute_motion_.v[0] += fabs(delta_trans * cs_bearing);
>     odom_integrator_absolute_motion_.v[1] += fabs(delta_trans * sn_bearing);
>     odom_integrator_absolute_motion_.v[2] += fabs(delta_rot);
> ```

I haven't gone through the math by hand on this section, but it seems to me that we could just jump to the end and add the absolute values of the x, y, and yaw deltas to the `odom_integrator_absolute_motion_`.  The only difference I can see is that we are zeroing out any bearing change if the translation was really, really small.  Does that if statement actually execute that often?  Is there something else that I'm missing?
</blockquote></details>

No, we are accumulating absolute motion on each update. So moving forward counts the same as moving back, as does turning right then left. So the results are different (and more correct if the gaussian noise is related to *absolute* motion).

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl_node.cpp, line 1195 at r12](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXe3Ea--8fFsUrPB8Jd:-LXeJ5hf51tGGr1mxXtE:b-k61t5t) ([raw file](https://github.com/badgertechnologies/navigation/blob/a1037e0487a57b0c6ad4ae4d567a6c0b62815f35/amcl/src/amcl_node.cpp#L1195)):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

It would be awesome if we could rely on our magnetometer here to give us better guesses at our orientation...something for the future...
</blockquote></details>

Yes, we are planning to add that here, and also to add it as one of the senors we use during the sensor update step.

**Review by travisariggs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/6)* status: all files reviewed, 6 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[amcl/src/amcl_node.cpp, line 1006 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXd_CQ17I1NP6L5iucP:-LXeLRxuCDwaEuO5jw6q:bsljsid) ([raw file](https://github.com/badgertechnologies/navigation/blob/9e28d9bd48d1018de43aaa0558672067520a5033/amcl/src/amcl_node.cpp#L1006)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

No, we are accumulating absolute motion on each update. So moving forward counts the same as moving back, as does turning right then left. So the results are different (and more correct if the gaussian noise is related to *absolute* motion).
</blockquote></details>

Right.  I'm asking why we don't simply do this:
```
    delta.v[0] = pose.v[0] - odom_integrator_last_pose_.v[0];
    delta.v[1] = pose.v[1] - odom_integrator_last_pose_.v[1];
    delta.v[2] = angle_diff(pose.v[2], odom_integrator_last_pose_.v[2]);

    // Accumulate absolute motion
    odom_integrator_absolute_motion_.v[0] += fabs(delta.v[0]);
    odom_integrator_absolute_motion_.v[1] += fabs(delta.v[1]);
    odom_integrator_absolute_motion_.v[2] += fabs(delta.v[2]);
```

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl_node.cpp, line 1250 at r13](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXe4OESBt5Z4am8X4gV:-LXeJbqf1KUSAcRl8oEO:b-6m7dfc) ([raw file](https://github.com/badgertechnologies/navigation/blob/77cba6dc90aa5c30efcc7399f3b6388852d6487f/amcl/src/amcl_node.cpp#L1250)):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

Just for my understanding, is the localizer multithreaded?  Is that why we have a lock?
</blockquote></details>

I have no idea. I didn't add this lock, it was there before.

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl_node.cpp, line 1222 at r12](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXe2gWP1ZcLOaKYJAwk:-LXeJZOr2w0CCaQsG1Km:b-f9a3mn) ([raw file](https://github.com/badgertechnologies/navigation/blob/a1037e0487a57b0c6ad4ae4d567a6c0b62815f35/amcl/src/amcl_node.cpp#L1222)):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

Just for my understanding, does this mean that we try to get a better pose, but if we try and try, we still end up with an almost totally random seed pose?  I guess this still makes it more likely that we will get a better seed pose.
</blockquote></details>

Egads thats a bug. I refactored this code to make it clearer and to fix this issue.

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl_node.cpp, line 1006 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXd_CQ17I1NP6L5iucP:-LXePn2ACtMnzRZLGdwk:bqgm51s) ([raw file](https://github.com/badgertechnologies/navigation/blob/9e28d9bd48d1018de43aaa0558672067520a5033/amcl/src/amcl_node.cpp#L1006)):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

Right.  I'm asking why we don't simply do this:
```
    delta.v[0] = pose.v[0] - odom_integrator_last_pose_.v[0];
    delta.v[1] = pose.v[1] - odom_integrator_last_pose_.v[1];
    delta.v[2] = angle_diff(pose.v[2], odom_integrator_last_pose_.v[2]);

    // Accumulate absolute motion
    odom_integrator_absolute_motion_.v[0] += fabs(delta.v[0]);
    odom_integrator_absolute_motion_.v[1] += fabs(delta.v[1]);
    odom_integrator_absolute_motion_.v[2] += fabs(delta.v[2]);
```
</blockquote></details>

Because I'm tracking motion from the base's point of view, I must rotate the frame of reference by the robots average bearing during the update. This way, I can accumulate absolute forward/backward motion independent of average strafing motion. For rotation, that is what I'm doing already, I think.

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/6)* status: 2 of 12 files reviewed, 5 unresolved discussions (waiting on @c-andy-martin, @howardcochran, and @travisariggs)

___
*[amcl/src/amcl/sensors/amcl_odom.cpp, line 97 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXdbf92-y-kNq4RZxDY:-LXePIMYC8WQtPaCDQpV:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/9e28d9bd48d1018de43aaa0558672067520a5033/amcl/src/amcl/sensors/amcl_odom.cpp#L97)):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

> ```
>                        double alpha2,
>                        double alpha3,
>                        double alpha4,
>                        double alpha5)
> ```

Should these args line up with the first argument?
</blockquote></details>

Done.

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl_node.cpp, line 1200 at r12](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXe2LII21tCeiNrsom6:-LXeRF9a48uy6iGSXrXd:b9t8hwh) ([raw file](https://github.com/badgertechnologies/navigation/blob/a1037e0487a57b0c6ad4ae4d567a6c0b62815f35/amcl/src/amcl_node.cpp#L1200)):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

If the `uniform_pose_starting_weight_threshold_` is zero, will this be an infinite loop?
</blockquote></details>

Yes, thats a bug. I fixed it in the subsequent commit.

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl_node.cpp, line 1222 at r12](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXe2gWP1ZcLOaKYJAwk:-LXeRJQq3m7qvNb7MPYa:b-s690rs) ([raw file](https://github.com/badgertechnologies/navigation/blob/a1037e0487a57b0c6ad4ae4d567a6c0b62815f35/amcl/src/amcl_node.cpp#L1222)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Egads thats a bug. I refactored this code to make it clearer and to fix this issue.
</blockquote></details>

Um, sorry, above comment was meant for your above comment. Right, if we are unable to get a good pose, we try again with a lower weight until we get one. A better solution would be to keep previous results in a priority queue and only add new entries to the queue as we do this, so if I got a past somewhat good result I could re-use it. That will be an improvement I make someday.

**Review by travisariggs — APPROVED** [review]
> Reviewed 10 of 10 files at r14, 4 of 4 files at r15, 4 of 4 files at r16, 4 of 4 files at r17, 4 of 4 files at r18, 1 of 1 files at r19, 2 of 2 files at r20, 2 of 2 files at r21.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @howardcochran)

**Review by 12tbuchman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/6)* status: all files reviewed, 1 unresolved discussion (waiting on @c-andy-martin and @howardcochran)

___
*[amcl/src/amcl_node.cpp, line 527 at r15](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXf279Y9_NKBMRWDEwX:-LXf279Z03FfCMlzuw-j:brbbh4d) ([raw file](https://github.com/badgertechnologies/navigation/blob/a9e5da269c84c443d301d08bcb2c110671615ed2/amcl/src/amcl_node.cpp#L527)):*
> ```cpp
>   else if(config.resample_model_type == "systematic")
>     resample_model_type_ = PF_RESAMPLE_SYSTEMATIC;
>   else
> ```

You might want to log something here to say that the resample model type was invalid and you are defaulting to multinomial.

**Review by 12tbuchman — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/6)* status: all files reviewed, 3 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[amcl/src/amcl/pf/pf.c, line 509 at r15](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXf47cx1-GhZlvxc9Bl:-LXf47cx1-GhZlvxc9Bm:b-w79q6i) ([raw file](https://github.com/badgertechnologies/navigation/blob/a9e5da269c84c443d301d08bcb2c110671615ed2/amcl/src/amcl/pf/pf.c#L509)):*
> ```C
>   return total;
> }
> ```

you have an extra linebreak here
___
*[amcl/src/amcl/pf/pf.c, line 541 at r15](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXf42HJ8GSxXIp9t4PH:-LXf42HJ8GSxXIp9t4PI:b-h9zdyq) ([raw file](https://github.com/badgertechnologies/navigation/blob/a9e5da269c84c443d301d08bcb2c110671615ed2/amcl/src/amcl/pf/pf.c#L541)):*
> ```C
>       break;
>   }
>   
> ```

extra spaces here

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl/pf/pf.c, line 509 at r15](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXf47cx1-GhZlvxc9Bl:-LXgLosg7KcysDE2nvlk:b7umhgq) ([raw file](https://github.com/badgertechnologies/navigation/blob/a9e5da269c84c443d301d08bcb2c110671615ed2/amcl/src/amcl/pf/pf.c#L509)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

you have an extra linebreak here
</blockquote></details>

This is intentional to match the style of the rest of the file.

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl/pf/pf.c, line 509 at r15](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXf47cx1-GhZlvxc9Bl:-LXgLroaCoS_QdNc-Jdk:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/a9e5da269c84c443d301d08bcb2c110671615ed2/amcl/src/amcl/pf/pf.c#L509)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This is intentional to match the style of the rest of the file.
</blockquote></details>

Done.

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl_node.cpp, line 527 at r15](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXf279Y9_NKBMRWDEwX:-LXgTQeN4tWYhjlds2wW:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/a9e5da269c84c443d301d08bcb2c110671615ed2/amcl/src/amcl_node.cpp#L527)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

You might want to log something here to say that the resample model type was invalid and you are defaulting to multinomial.
</blockquote></details>

Done.

**Comment by c-andy-martin** [comment]
___
*[amcl/src/amcl/pf/pf.c, line 541 at r15](https://reviewable.io/reviews/badgertechnologies/navigation/6#-LXf42HJ8GSxXIp9t4PH:-LXgTT2I3viKBjCgQeDI:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/a9e5da269c84c443d301d08bcb2c110671615ed2/amcl/src/amcl/pf/pf.c#L541)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

extra spaces here
</blockquote></details>

Done.

**Review by c-andy-martin — COMMENTED** [review]
> Dismissed @12tbuchman from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/6)* status: 4 of 12 files reviewed, all discussions resolved (waiting on @howardcochran and @travisariggs)

**Pull request merged**
