### PR TITLE
Costmap 3d query improvements

### PR DESCRIPTION
**Pull request by c-andy-martin**
Last (4 of 4) nav PR for 20 Hz planning

- - -
This change is [Reviewable](https://reviewable.io/reviews/BadgerTechnologies/navigation/52)

### CODE REVIEW

**Review by bobhenz-jabil — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 5 of 5 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, 25 of 25 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/navigation/52)* status: all files reviewed, 3 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[`-- commits` line 147 at r11](https://reviewable.io/reviews/BadgerTechnologies/navigation/52#-NsELUVS-5S8soYshoOr):*
praise: Thanks for doing this. :smile: 
___
*[`-- commits` line 152 at r11](https://reviewable.io/reviews/BadgerTechnologies/navigation/52#-NsELpurCv0I3A4IiRuR):*
typo: Varoius should be Various
___
*[`costmap_3d/CMakeLists.txt` line 139 at r9](https://reviewable.io/reviews/BadgerTechnologies/navigation/52#-NsEKoTaCb7Xsfo7OLXG:-NsEKoTaCb7Xsfo7OLXH:bold72d) ([raw file](https://github.com/BadgerTechnologies/navigation/blob/d44e5897b560d7fb148fc38e275ecf3cd8fc41fc/costmap_3d/CMakeLists.txt#L139)):*
> ```CMake
> if(CATKIN_ENABLE_TESTING)
>   find_package(badger_test_lib)
>   badger_add_rostest_gtest(
> ```

From what I see of your test, I think you should use `badger_add_gtest()` instead of `badger_add_rostest_gtest()` since you are not actually loading ROS nodes that you are testing against. Then you don't need a .test file and it won't take time spinning up a roscore, etc.
___
*[`costmap_3d/src/costmap_3d_query.cpp` line 421 at r6](https://reviewable.io/reviews/BadgerTechnologies/navigation/52#-NsEFkHl14azyGVvk22o:-NsEFkHl14azyGVvk22p:be4sl0t) ([raw file](https://github.com/BadgerTechnologies/navigation/blob/60c7a61cb044b1d7d2855895b76673692d0293e7/costmap_3d/src/costmap_3d_query.cpp#L421)):*
> ```cpp
>             // The node exists and has no children (so its a leaf and not an
>             // inner node), is at the correct depth and is considered occupied
>             // for the proper octree. Keep this entry.
> ```

Seems like the above chunk of code is repeated, once for the distance_cache_ and another for the milli_distance_cache_. Future improvement might be to make those caches a class with this as a method?

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/navigation/52)* status: 2 of 31 files reviewed, 1 unresolved discussion (waiting on @bobhenz-jabil and @howardcochran)

___
*[`costmap_3d/CMakeLists.txt` line 139 at r9](https://reviewable.io/reviews/BadgerTechnologies/navigation/52#-NsEKoTaCb7Xsfo7OLXG:-NsJwA7N7ENlofCnTUuc:b-d5q2i1) ([raw file](https://github.com/BadgerTechnologies/navigation/blob/d44e5897b560d7fb148fc38e275ecf3cd8fc41fc/costmap_3d/CMakeLists.txt#L139)):*
<details><summary><i>Previously, bobhenz-jabil (Bob Henz) wrote…</i></summary><blockquote>

From what I see of your test, I think you should use `badger_add_gtest()` instead of `badger_add_rostest_gtest()` since you are not actually loading ROS nodes that you are testing against. Then you don't need a .test file and it won't take time spinning up a roscore, etc.
</blockquote></details>

Fixed. Thanks!
___
*[`costmap_3d/src/costmap_3d_query.cpp` line 421 at r6](https://reviewable.io/reviews/BadgerTechnologies/navigation/52#-NsEFkHl14azyGVvk22o:-NsJwRLB8H1TTmBc6L1C:b1nhvvv) ([raw file](https://github.com/BadgerTechnologies/navigation/blob/60c7a61cb044b1d7d2855895b76673692d0293e7/costmap_3d/src/costmap_3d_query.cpp#L421)):*
<details><summary><i>Previously, bobhenz-jabil (Bob Henz) wrote…</i></summary><blockquote>

Seems like the above chunk of code is repeated, once for the distance_cache_ and another for the milli_distance_cache_. Future improvement might be to make those caches a class with this as a method?
</blockquote></details>

Done. This took quite some time, but I abstracted all the details of the distance caches into their own object, and now none of it is repeated anywhere.

**Review by c-andy-martin — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 5 files at r8, 2 of 3 files at r13, 23 of 26 files at r15, 1 of 1 files at r16, 2 of 2 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/navigation/52)* status: all files reviewed, 1 unresolved discussion (waiting on @bobhenz-jabil and @howardcochran)

**Review by bobhenz-jabil — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r13, 23 of 26 files at r15, 1 of 1 files at r16, 2 of 2 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/navigation/52)* status: all files reviewed, 1 unresolved discussion (waiting on @c-andy-martin and @howardcochran)

___
*[`Jenkinsfile` line 34 at r18](https://reviewable.io/reviews/BadgerTechnologies/navigation/52#-NvrvLojC80ldvjLsyKQ:-NvrvLojC80ldvjLsyKR:b-b17re8) ([raw file](https://github.com/BadgerTechnologies/navigation/blob/63a3e387bb1eb6de45bcfc4ea111ccd0b4c955ad/Jenkinsfile#L34)):*
> ```Groovy
>     }
>   }
> }
> ```

Instead of adding this Jenkins file, please add a github workflow by copying this file into your repo (into a similarly named path): https://github.com/BadgerTechnologies/motor_driver/blob/develop/.github/workflows/workflow.yaml
This is one of those cases where about 1/2-way through the process of getting linting setup on every repo @dandedrick found a better way and we decided to push forward with the new way but to not go back and re-do all the ones we had already completed. :roll_eyes:

**Review by c-andy-martin — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/navigation/52)* status: all files reviewed, 1 unresolved discussion (waiting on @dandedrick and @howardcochran)

___
*[`Jenkinsfile` line 34 at r18](https://reviewable.io/reviews/BadgerTechnologies/navigation/52#-NvrvLojC80ldvjLsyKQ:-Nw5qZwEEQwMwh6hCul4:b-v35nmj) ([raw file](https://github.com/BadgerTechnologies/navigation/blob/63a3e387bb1eb6de45bcfc4ea111ccd0b4c955ad/Jenkinsfile#L34)):*
<details><summary><i>Previously, bobhenz-jabil (Bob Henz) wrote…</i></summary><blockquote>

Instead of adding this Jenkins file, please add a github workflow by copying this file into your repo (into a similarly named path): https://github.com/BadgerTechnologies/motor_driver/blob/develop/.github/workflows/workflow.yaml
This is one of those cases where about 1/2-way through the process of getting linting setup on every repo @dandedrick found a better way and we decided to push forward with the new way but to not go back and re-do all the ones we had already completed. :roll_eyes:
</blockquote></details>

As we discussed, b/c this is a public repo we need to use the Jenkinfile mechanism, so I went back to it

**Review by bobhenz-jabil — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/navigation/52)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @howardcochran)

**Pull request merged**
