### PR TITLE
Costmap 3d query improvements

### PR DESCRIPTION
**Pull request by c-andy-martin**
Several improvements to costmap 3d queries:

* Handle interior collisions
* Handle penetration-based signed distance
* Add more caching to improve performance (milli cache, exact cache, last cache)
* Make queries thread safe using read/write locking
* Publish the actual padded foot print
* Fix deadlock in octomap server plugin
* Some small bug fixes and testing changes
* Add query tracking statistics using atomic variables to aid in performance analysis

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/10)

### CODE REVIEW

**Review by howardcochran — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, 2 of 2 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 1 of 1 files at r17, 3 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/10)* status: all files reviewed, 6 unresolved discussions (waiting on @c-andy-martin)

___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 135 at r5](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjKI3x7oh8rBegDOeW:-LyjKI3x7oh8rBegDOeX:bao7ffy) ([raw file](https://github.com/badgertechnologies/navigation/blob/b78def870cfb0f8f1cf745a91c2e695682989351/costmap_3d/include/costmap_3d/costmap_3d_query.h#L135)):*
> ```objc
>    * obtained by a small perturbation in pose will point away from the
>    * penetration. However, if the pose is moved enough away from the
>    * penetration, some other pentrating point me choosen in the case of
> ```

s/me/may be/  (I suppose)
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 192 at r7](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjLQj6BEDU3JQUh3_x:-LyjLQj6BEDU3JQUh3_y:bxwqh5d) ([raw file](https://github.com/badgertechnologies/navigation/blob/49000f2cc1af63b03ad82628535356d99fdf71a6/costmap_3d/include/costmap_3d/costmap_3d_query.h#L192)):*
> ```objc
>   std::shared_ptr<const octomap::OcTree> octree_ptr_;
>   FCLCollisionObjectPtr world_obj_;
>   inline const fcl::Transform3<FCLFloat> getFCLTransform(const geometry_msgs::Pose& pose)
> ```

Minor nit: This function appears to just convert its input from one data type to another. If that's  true, I would prefer that it be named something different like poseToFCLTransform or FCLTransformFromPose or whatever.  Because the name suggests that it is going to look up or "get" a value from somewhere or that it is an accessor for a member variable.
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 216 at r7](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjMFGh89DLx3Xm1X5X:-LyjMFGi7YEr5HfJ7fFm:b-8kjhdx) ([raw file](https://github.com/badgertechnologies/navigation/blob/49000f2cc1af63b03ad82628535356d99fdf71a6/costmap_3d/include/costmap_3d/costmap_3d_query.h#L216)):*
> ```objc
>       float dist = sqrt(x * x + y * y);
>       float nx = x / dist;
>       float ny = y / dist;
> ```

Assuming this is only used on the robot mesh, it is true that dist can never be zero, but should this code make that assumption?  Conceivably, one could do queries using a custom mesh that has a point at he origin, I think.  Or even anywhere x=0 or y=0 lines.
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 222 at r7](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjMdqi0g4Ouip9hfPE:-LyjMdqi0g4Ouip9hfPF:blwe0ii) ([raw file](https://github.com/badgertechnologies/navigation/blob/49000f2cc1af63b03ad82628535356d99fdf71a6/costmap_3d/include/costmap_3d/costmap_3d_query.h#L222)):*
> ```objc
>   }
> 
>   // Convert PCL point to FCL
> ```

Useless comment
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 228 at r7](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjMmjy-wUdK-u-7w5Y:-LyjMmjy-wUdK-u-7w5Z:blwe0ii) ([raw file](https://github.com/badgertechnologies/navigation/blob/49000f2cc1af63b03ad82628535356d99fdf71a6/costmap_3d/include/costmap_3d/costmap_3d_query.h#L228)):*
> ```objc
>   }
> 
>   // Convert FCL point to PCL
> ```

Useless comment
___
*[costmap_3d/include/costmap_3d/crop_hull.h, line 126 at r18](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjZiEbEliVLXZpgr0F:-LyjZiEbEliVLXZpgr0G:b-uwgqbt) ([raw file](https://github.com/badgertechnologies/navigation/blob/31120f41546d00a4c12f8c815c3fa58a43332064/costmap_3d/include/costmap_3d/crop_hull.h#L126)):*
> ```objc
>         Eigen::Vector3f(0.264882f,  0.688399f, 0.675237f),
>         Eigen::Vector3f(0.0145419f, 0.732901f, 0.68018f),
>         Eigen::Vector3f(0.856514f,  0.508771f, 0.0868081f)
> ```

What do all these magic numbers mean?
___
*[costmap_3d/src/costmap_3d_query.cpp, line 129 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjH8mX7wzFTExe7J2q:-LyjH8mYE7gI2Q2jybUX:by3i2p2) ([raw file](https://github.com/badgertechnologies/navigation/blob/ebbb484769549518f64abc16e13d228b1156ab20/costmap_3d/src/costmap_3d_query.cpp#L129)):*
> ```cpp
>     // The costmap has been updated since the last query, reset our caches
>     if (force_cache_dump || last_layered_costmap_update_number_ != layered_costmap_3d_->getNumberOfUpdates())
>     {
> ```

As I read this logic, it appears to me that if either of these conditions is true:

1. layered_costmap_3d_->getCostmap3D() != octree_ptr_
2. last_layered_costmap_update_number_ != layered_costmap_3d_->getNumberOfUpdates()))

...then we will have set need_update to true above.  Those two conditions are re-tested again here and a few lines above, which seems to me that it should render the force_cache_dump flag unnecessary.  In other words, it looks like any time need_update is set true it will necessarily also dump the cache.  So either that is a bug or this logic could be simplified to just just dump the cache any time need_update is true.

Unless you expect something to have changed by the time you upgrade to unique lock.  In that case, a comment is needed to explain why we're retesting and introducing the force_cache_dump flag.

Or I could just be misreading it :shrug:
___
*[costmap_3d/src/costmap_3d_query.cpp, line 313 at r7](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjPSodCe8YZ0O7tVYI:-LyjPSodCe8YZ0O7tVYJ:b-dqp63z) ([raw file](https://github.com/badgertechnologies/navigation/blob/49000f2cc1af63b03ad82628535356d99fdf71a6/costmap_3d/src/costmap_3d_query.cpp#L313)):*
> ```cpp
>     // that does nothing, and ensure the crop_hull goes out of scope before the
>     // test_cloud.
>     pcl::PointCloud<pcl::PointXYZ>::Ptr test_cloud_ptr(&test_cloud, [](void *){});
> ```

Ah, nice trick!
___
*[costmap_3d/src/costmap_3d_query.cpp, line 390 at r13](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjWQ5c26zaIex0JgK7:-LyjWQ5c26zaIex0JgK8:b-9enm00) ([raw file](https://github.com/badgertechnologies/navigation/blob/9522c7c909bd9ea9604dff57901ece07da4036a5/costmap_3d/src/costmap_3d_query.cpp#L390)):*
> ```cpp
>   {
>     return exact_cache_entry->second;
>   }
> ```

I'm curious how often we do exact repeated queries
___
*[costmap_3d/src/costmap_3d_query.cpp, line 193 at r16](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjXleyDi-Tj-LveaMT:-LyjXlez8xNZYoYaiF7j:btuw87n) ([raw file](https://github.com/badgertechnologies/navigation/blob/7305b3bdbf64a98a57d5c48c63c8f84646d1c785/costmap_3d/src/costmap_3d_query.cpp#L193)):*
> ```cpp
>       micro_hits_since_clear_ -
>       exact_hits_since_clear_;
>   double hit_ratio = (double)hits_since_clear_ / queries_since_clear_;
> ```

Can the denom be zero?
___
*[costmap_3d/src/costmap_3d_query.cpp, line 204 at r16](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjXzHv8zlygFC6_ZgI:-LyjXzHv8zlygFC6_ZgJ:b-8hebjw) ([raw file](https://github.com/badgertechnologies/navigation/blob/7305b3bdbf64a98a57d5c48c63c8f84646d1c785/costmap_3d/src/costmap_3d_query.cpp#L204)):*
> ```cpp
>       micro_hits_since_clear_us_ +
>       exact_hits_since_clear_us_;
>   ROS_DEBUG_STREAM_NAMED(
> ```

It might be nice to skip this if queries_size_clear_ is zero (or even if it's just small) so that it will be quiet if we're idle.

**Comment by c-andy-martin** [comment]
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 216 at r7](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjMFGh89DLx3Xm1X5X:-LykU4qSAw0lmysuofAh:b-5wd1w7) ([raw file](https://github.com/badgertechnologies/navigation/blob/49000f2cc1af63b03ad82628535356d99fdf71a6/costmap_3d/include/costmap_3d/costmap_3d_query.h#L216)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Assuming this is only used on the robot mesh, it is true that dist can never be zero, but should this code make that assumption?  Conceivably, one could do queries using a custom mesh that has a point at he origin, I think.  Or even anywhere x=0 or y=0 lines.
</blockquote></details>

good catch. I copied this from Bob's safety velocity code, I'll make a PR on that code too

**Comment by c-andy-martin** [comment]
___
*[costmap_3d/include/costmap_3d/crop_hull.h, line 126 at r18](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjZiEbEliVLXZpgr0F:-LykVjQeDypg6n_tOYGD:b-kyuvbj) ([raw file](https://github.com/badgertechnologies/navigation/blob/31120f41546d00a4c12f8c815c3fa58a43332064/costmap_3d/include/costmap_3d/crop_hull.h#L126)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

What do all these magic numbers mean?
</blockquote></details>

I copied this from PCL, they are essentially random numbers.

**Comment by c-andy-martin** [comment]
___
*[costmap_3d/src/costmap_3d_query.cpp, line 193 at r16](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjXleyDi-Tj-LveaMT:-LykW3UkD4GAMDq-24Rt:b-7rap43) ([raw file](https://github.com/badgertechnologies/navigation/blob/7305b3bdbf64a98a57d5c48c63c8f84646d1c785/costmap_3d/src/costmap_3d_query.cpp#L193)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Can the denom be zero?
</blockquote></details>

yes, and then the prints are NaN, which is fine.

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/10)* status: all files reviewed, 2 unresolved discussions (waiting on @c-andy-martin)

___
*[costmap_3d/src/costmap_3d_query.cpp, line 390 at r13](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjWQ5c26zaIex0JgK7:-LykWMfIC31jAF_Jfplw:bftrxko) ([raw file](https://github.com/badgertechnologies/navigation/blob/9522c7c909bd9ea9604dff57901ece07da4036a5/costmap_3d/src/costmap_3d_query.cpp#L390)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I'm curious how often we do exact repeated queries
</blockquote></details>

When on a full path, this seems to be about 50 or so, saving about 70 microseconds. Its pretty cheap to maintain and check, as there is no binning. An exact hit takes <<1 usec (something like 50 nanoseconds on average). We basically re-query the final path 3 times, once for the last optimization run in teb, once in the costmap model in teb, and once again in the costmap model in the teb flex wrapper.

**Review by c-andy-martin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/10)* status: all files reviewed, 2 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/src/costmap_3d_query.cpp, line 204 at r16](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjXzHv8zlygFC6_ZgI:-LyoM0KO0BXL8utuOmfi:b-rjapz9) ([raw file](https://github.com/badgertechnologies/navigation/blob/7305b3bdbf64a98a57d5c48c63c8f84646d1c785/costmap_3d/src/costmap_3d_query.cpp#L204)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

It might be nice to skip this if queries_size_clear_ is zero (or even if it's just small) so that it will be quiet if we're idle.
</blockquote></details>

because checkCostmap (which calls printStatistics) is only called when queries are being made, this naturally quiets itself, as we simply won't print when no one is querying the costmap.

**Comment by c-andy-martin** [comment]
___
*[costmap_3d/src/costmap_3d_query.cpp, line 129 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjH8mX7wzFTExe7J2q:-LyoMZ69DblwpevEGtvw:b-886gsx) ([raw file](https://github.com/badgertechnologies/navigation/blob/ebbb484769549518f64abc16e13d228b1156ab20/costmap_3d/src/costmap_3d_query.cpp#L129)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

As I read this logic, it appears to me that if either of these conditions is true:

1. layered_costmap_3d_->getCostmap3D() != octree_ptr_
2. last_layered_costmap_update_number_ != layered_costmap_3d_->getNumberOfUpdates()))

...then we will have set need_update to true above.  Those two conditions are re-tested again here and a few lines above, which seems to me that it should render the force_cache_dump flag unnecessary.  In other words, it looks like any time need_update is set true it will necessarily also dump the cache.  So either that is a bug or this logic could be simplified to just just dump the cache any time need_update is true.

Unless you expect something to have changed by the time you upgrade to unique lock.  In that case, a comment is needed to explain why we're retesting and introducing the force_cache_dump flag.

Or I could just be misreading it :shrug:
</blockquote></details>

Fixed

**Comment by c-andy-martin** [comment]
___
*[costmap_3d/src/costmap_3d_query.cpp, line 129 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/10#-LyjH8mX7wzFTExe7J2q:-LyoP7fI4Tg1Xiq7ujLJ:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/ebbb484769549518f64abc16e13d228b1156ab20/costmap_3d/src/costmap_3d_query.cpp#L129)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

Done.

**Review by howardcochran — APPROVED** [review]
> Reviewed 1 of 3 files at r20, 2 of 4 files at r21, 1 of 1 files at r23, 2 of 3 files at r24, 1 of 1 files at r25.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
