### PR TITLE
Navfn dyncfg

### PR DESCRIPTION
**Pull request by howardcochran**
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/17)

### CODE REVIEW

**Comment by c-andy-martin** [comment]
___
*[navfn/CMakeLists.txt, line 31 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/17#-M4_veiq-vptU_nwsE3y:-M4_veiq-vptU_nwsE3z:blf92qe) ([raw file](https://github.com/badgertechnologies/navigation/blob/73757aaf6cd1ebe378b2ae84f074ebb8acfa7dbe/navfn/CMakeLists.txt#L31)):*
> ```CMake
> add_definitions(${EIGEN3_DEFINITIONS})
> 
> set(CMAKE_CXX_STANDARD 11)
> ```

seems like this should be higher in the file so if we have to remove it or alter it its easy to find?

**Comment by c-andy-martin** [comment]
___
*[navfn/include/navfn/navfn_ros.h, line 176 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/17#-M4_w-P9Dhp8RSHYSbox:-M4_w-PA4YKFTICBX_eM:b7uk8to) ([raw file](https://github.com/badgertechnologies/navigation/blob/73757aaf6cd1ebe378b2ae84f074ebb8acfa7dbe/navfn/include/navfn/navfn_ros.h#L176)):*
> ```objc
>       pcl_ros::Publisher<PotarrPoint> potarr_pub_;
>       bool initialized_, allow_unknown_, visualize_potential_;
>       std::shared_ptr<dynamic_reconfigure::Server<navfn::NavfnROSConfig> > dyncfg_srv_;
> ```

seems like this could just be a `unique_ptr`

**Comment by c-andy-martin** [comment]
___
*[navfn/src/navfn_ros.cpp, line 106 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/17#-M4_woMw79Zys8HS3pj9:-M4_woMw79Zys8HS3pjA:brcne9) ([raw file](https://github.com/badgertechnologies/navigation/blob/73757aaf6cd1ebe378b2ae84f074ebb8acfa7dbe/navfn/src/navfn_ros.cpp#L106)):*
> ```cpp
>     allow_unknown_ = config.allow_unknown;
>     default_tolerance_ = config.default_tolerance;
>     ROS_INFO_STREAM("NavfnROS Reconfig: allow_unknown: " << (allow_unknown_ ? "true" : "false")
> ```

learned a cool trick, instead you can do:
```
... << std::boolalpha << allow_unknown_
```
and include `<iomanip>`

**Review by c-andy-martin — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/17)* status: all files reviewed, 3 unresolved discussions (waiting on @howardcochran)

**Review by howardcochran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/17)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @c-andy-martin)

___
*[navfn/include/navfn/navfn_ros.h, line 176 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/17#-M4_w-P9Dhp8RSHYSbox:-M4a-7nK6OuARpSlt5-x:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/73757aaf6cd1ebe378b2ae84f074ebb8acfa7dbe/navfn/include/navfn/navfn_ros.h#L176)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

seems like this could just be a `unique_ptr`
</blockquote></details>

Done.
___
*[navfn/src/navfn_ros.cpp, line 106 at r1](https://reviewable.io/reviews/badgertechnologies/navigation/17#-M4_woMw79Zys8HS3pj9:-M4a-8MZAEaq323XKzjU:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/73757aaf6cd1ebe378b2ae84f074ebb8acfa7dbe/navfn/src/navfn_ros.cpp#L106)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

learned a cool trick, instead you can do:
```
... << std::boolalpha << allow_unknown_
```
and include `<iomanip>`
</blockquote></details>

Done.

**Review by c-andy-martin — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/17#-:-M4a-kb525wy1gdhCtUS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
